# Generated by Django 4.1.4 on 2023-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
