# Generated by Django 4.1.4 on 2022-12-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='date',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
