# Generated by Django 4.1.4 on 2022-12-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_remove_bankaccount_date_bankaccount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='owner',
        ),
    ]
