name: backend CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: |
        cd src/backend
        pipenv install --deploy
    - name: Run Tests
      run: |
        cd src/backend
        pipenv run python manage.py test
